# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
  branches:
    include:
    - releases/*

# Disable PullRequest Validation
pr: none

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: Use .NET 6.0
  inputs:
    packageType: 'sdk'
    version: '6.0.x'

- task: PowerShell@2
  displayName: 'Set Version Numbers'
  inputs:
    targetType: 'inline'
    script: |
      Install-PackageProvider -Name NuGet -Force -Scope CurrentUser
      Install-Module -Name PoShPipeline -Force -Verbose -Scope CurrentUser
      Import-Module -Name PoShPipeline
      
      New-Release -Path '$(Build.SourcesDirectory)\src' -BranchName $(Build.SourceBranch) -BuildNumber $(Build.BuildID)

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  displayName: 'Restore'
  inputs:
    restoreSolution: '$(solution)'
    
- task: DotNetCoreCLI@2
  displayName: 'DotNet Pack Lineup.Core'
  inputs:
    command: 'pack'
    packagesToPack: '$(Build.SourcesDirectory)\src\ITfoxtec.Identity.Saml2.MvcCore\ITfoxtec.Identity.Saml2.MvcCore.csproj'
    versioningScheme: 'off'
    buildProperties: 'PackageID=Lineup.Saml2.MvcCore'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artefacts(pipeline only)'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'Lineup.Saml2.MvcCore'
    publishLocation: 'Container'

- task: DotNetCoreCLI@2
  displayName: 'Publish libs to Azure Artefacts (InfraFeed)'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '1337e375-d86a-43a4-91ab-3766b3b9e0eb/db365ce0-dfa4-4e59-badb-b20d77494b14'